# syntax=docker/dockerfile:1
FROM varnish:7.6

LABEL maintainer="ServicioSocial2026-1 <ss.labgeomatica.pagina@gmail.com>" \
      org.label-schema.name="plone-lab-varnish" \
      org.label-schema.description="LGyED_DICyG Varnish image." \
      org.label-schema.vendor="ServicioSocial2026-1"

COPY etc/varnish.vcl /etc/varnish/default.vcl
